### PR TITLE
Combine client and server download pages

### PR DESCRIPTION
**Pull request by thornbill**
Combines the client and server download pages to help with reports of people accidentally downloading the server when they mean to download a client (hopefully)...

Screenshot 2022-12-09 at 01-26-29 Clients Jellyfin

Screenshot 2022-12-09 at 01-26-51 Downloads Jellyfin

### CODE REVIEW

**Comment by thornbill** [comment]
Screenshot 2022-12-09 at 02-14-47 Clients Jellyfin

Updated header margins

**Comment by nielsvanvelzen** [comment]
Maybe the stable/unstable toggle should be in a filters thingy too so it's consistent?

**Comment by thornbill** [comment]
I don't know... that might be weird since there are only the 2 options :man_shrugging:

**Comment by nielsvanvelzen** [comment]
With #294 it might make sense

**Comment by joshuaboniface** [comment]
> With #294 it might make sense, add a second toggle for "easy install" and "advanced install" instructions

I explicitly didn't want to do this, hiding it behind another button is just cumbersom esoecially when it only applies to a single platform.

**Review by nielsvanvelzen — APPROVED** [review]

**Pull request merged**
