### PR TITLE
Add Manet to the clients list

### PR DESCRIPTION
**Pull request by bzf**
First of all - thank you all for your hard work on Jellyfin! It really is a great piece of software 🙌🏽 

I'm the developer of the [Manet](https://tilo.dev/manet/) music app for iOS and got sent a link to [this form post](https://forum.jellyfin.org/t-ios-carplay-client-for-music-manet?pid=22475#pid22475) that suggests that you might accept paid apps for the jellyfin.org website, so I thought I'd send this PR to open the discussion about being added.

### CODE REVIEW

**Comment by JPVenson** [comment]
Hey there,
Thank you for creating this app, however i need to ask you if you would be willing to publish the sourcecode in an FOSS compatible licence as your list of requirements sets this as an important point.

https://jellyfin.org/docs/general/clients/#requirements-for-inclusion-in-all-clients

**Comment by bzf** [comment]
@JPVenson Ah, I missed that point! I was reading on the _Recommended clients_ requirements and missed that point. I don't intend on moving the app into a FOSS license for the time being, I guess we should close this PR then?

Sorry for not reading it through properly 🙈

**Comment by JPVenson** [comment]
Thats sad, we can still discuss internally if the app warents an exclusion from that rule because there are some points we might consider if you want to keep the request up.

**Comment by bzf** [comment]
Sure thing, I'd be happy to be listed on the website if possible. I can re-open it and I'll leave it to you to decide to merge or close it later on then 😊

**Review by nielsvanvelzen — APPROVED** [review]
Discussed with core team and we'd be happy to include Manet in our listing!

**Pull request merged**
