### PR TITLE
Update nginx.md

### PR DESCRIPTION
**Pull request by tempookian**

### CODE REVIEW

**Comment by nielsvanvelzen** [comment]
There are multiple `proxy_pass` lines across the different config samples and you only changed a single one. Can you describe why you made this change?

**Comment by tempookian** [comment]
my apologies for the lack of explanation. I tried on a server that is being proxied through Cloudflare. The way I changed the line worked. The other methods (lines in the post) I have not tried. Hence, I did not change them

**Comment by joshuaboniface** [comment]
Can you provide more details on why this change is being made and what it fixes? From my understanding, NGiNX will always start the proxy pass with `/` because the incoming URL would always start with `/`, so this shouldn't be necessary.

**Comment by nielsvanvelzen** [comment]
The trailing slash should not be necessary. Closing this PR as stale.

**Pull request closed without merging**
