### PR TITLE
translate VAProfile to Jellyfin Setting

### PR DESCRIPTION
**Pull request by jumoog**
it is not clear what each VAProfile means

Just parsing the vainfo output and setting up the correct settings might be easier.

### CODE REVIEW

**Comment by felix920506** [comment]
please fix the linter issues.

**Comment by gnattu** [comment]
LGTM in general, but I prefer the table like this,:

| Jellyfin Setting | VA-API Profil                                                                                         |
|------------------|-------------------------------------------------------------------------------------------------------|
| H264             | VAProfileH264Baseline<br>VAProfileH264Main<br>VAProfileH264High<br>VAProfileH264ConstrainedBaseline   |
| HEVC             | VAProfileHEVCMain                                                                                     |
| MPEG2            | VAProfileMPEG2Simple<br>VAProfileMPEG2Main                                                            |
| VC1              | VAProfileVC1Simple<br>VAProfileVC1Main<br>VAProfileVC1Advanced                                        |
| VP8              | VAProfileVP8Version0<br>VAProfileVP8Version1<br>VAProfileVP8Version2<br>VAProfileVP8Version3          |
| VP9              | VAProfileVP9Profile0                                                                                  |
| AV1              | VAProfileAV1Profile0                                                                                  |
| HEVC 10bit       | VAProfileHEVCMain10                                                                                   |
| VP9 10bit        | VAProfileVP9Profile2                                                                                  |




```
| Jellyfin Setting | VA-API Profil                                                                                         |
|------------------|-------------------------------------------------------------------------------------------------------|
| H264             | VAProfileH264Baseline<br>VAProfileH264Main<br>VAProfileH264High<br>VAProfileH264ConstrainedBaseline   |
| HEVC             | VAProfileHEVCMain                                                                                     |
| MPEG2            | VAProfileMPEG2Simple<br>VAProfileMPEG2Main                                                            |
| VC1              | VAProfileVC1Simple<br>VAProfileVC1Main<br>VAProfileVC1Advanced                                        |
| VP8              | VAProfileVP8Version0<br>VAProfileVP8Version1<br>VAProfileVP8Version2<br>VAProfileVP8Version3          |
| VP9              | VAProfileVP9Profile0                                                                                  |
| AV1              | VAProfileAV1Profile0                                                                                  |
| HEVC 10bit       | VAProfileHEVCMain10                                                                                   |
| VP9 10bit        | VAProfileVP9Profile2                                                                                  |

```

**Comment by jumoog** [comment]
> LGTM in general, but I prefer the table like this:
> Jellyfin Setting 	VA-API Profil
> H264 	VAProfileH264Baseline
> VAProfileH264Main
> VAProfileH264High
> VAProfileH264ConstrainedBaseline
> HEVC 	VAProfileHEVCMain
> MPEG2 	VAProfileMPEG2Simple
> VAProfileMPEG2Main
> VC1 	VAProfileVC1Simple
> VAProfileVC1Main
> VAProfileVC1Advanced
> VP8 	VAProfileVP8Version0
> VAProfileVP8Version1
> VAProfileVP8Version2
> VAProfileVP8Version3
> VP9 	VAProfileVP9Profile0
> AV1 	VAProfileAV1Profile0
> HEVC 10bit 	VAProfileHEVCMain10
> VP9 10bit 	VAProfileVP9Profile2
> 
> ```
> | Jellyfin Setting | VA-API Profil                                                                                         |
> |------------------|-------------------------------------------------------------------------------------------------------|
> | H264             | VAProfileH264Baseline<br>VAProfileH264Main<br>VAProfileH264High<br>VAProfileH264ConstrainedBaseline   |
> | HEVC             | VAProfileHEVCMain                                                                                     |
> | MPEG2            | VAProfileMPEG2Simple<br>VAProfileMPEG2Main                                                            |
> | VC1              | VAProfileVC1Simple<br>VAProfileVC1Main<br>VAProfileVC1Advanced                                        |
> | VP8              | VAProfileVP8Version0<br>VAProfileVP8Version1<br>VAProfileVP8Version2<br>VAProfileVP8Version3          |
> | VP9              | VAProfileVP9Profile0                                                                                  |
> | AV1              | VAProfileAV1Profile0                                                                                  |
> | HEVC 10bit       | VAProfileHEVCMain10                                                                                   |
> | VP9 10bit        | VAProfileVP9Profile2                                                                                  |
> ```

Yes looks better this way

**Comment by gnattu** [comment]
Sorry, our CI wants the newline tag to be a closing tag `<br/>` instead of `<br>`. Can you update that?

**Review by Shadowghost — APPROVED** [review]

**Pull request merged**
