### PR TITLE
Add client to "Clients" page

### PR DESCRIPTION
**Pull request by manuel-rw**
Hi 👋

I would like to add my open source project to the list of available clients.
Please let me know if I should change anything or if the commit message is fine.

### CODE REVIEW

**Review by nielsvanvelzen — COMMENTED** [review]
Thanks for adding! I think we should add something like ` (by [username])` to the names of both discord music bots to avoid confusion between the two.

**Comment by manuel-rw** [comment]
> Thanks for adding! I think we should add something like ` (by [username])` to the names of both discord music bots to avoid confusion between the two.

Yes, that is a good idea.
I will add that as soon as possible.

**Comment by manuel-rw** [comment]
image

This is how it looks on my development server. Do you think that the "by XYZ" should be in the title instead, or is this "enough"?

**Comment by nielsvanvelzen** [comment]
When scanning a page I mostly look at the titles, so IMO the author name should be in the title.

**Comment by manuel-rw** [comment]
Okay, makes sense. I'll also fix the eslint warning...

**Comment by manuel-rw** [comment]
image

**Review by nielsvanvelzen — APPROVED** [review]
Thanks!

**Pull request merged**
