### PR TITLE
Update nginx.md

### PR DESCRIPTION
**Pull request by Ladrien-git**
Updating the NGINX config to disable insecure TLS 1.0 and 1.1 version

### CODE REVIEW

**Review by felix920506 — CHANGES_REQUESTED** [review]
There are many older devices out there that might not support TLS 1.2+ and this setting might break those clients. There should at least be a warning

Maybe change it to
```
    # Uncomment next line to Disable TLS 1.0 and 1.1 (Might break older devices)
    # ssl_protocols TLSv1.3 TLSv1.2;
```

**Review by felix920506 — APPROVED** [review]
Looks good to me

**Review by nielsvanvelzen — APPROVED** [review]

**Comment by DX37** [comment]
There's no point in this change. `/etc/letsencrypt/options-ssl-nginx.conf` already contain this line. After uncommeting that line in nginx config it would print warning about duplicating.
image

**Comment by DX37** [comment]
That's applies to Let's Encrypt usage, so maybe at least leave a warning about it?

**Pull request merged**
