### PR TITLE
Create fail2ban_upstream_proxy_chain_setup_guide.md

### PR DESCRIPTION
**Pull request by famesjranko**
ADD: proposed guide for setting up Fail2Ban to manage IP bans on an upstream reverse proxy server -  handy in situations where jellyfin and reverse proxy are on different hosts.

### CODE REVIEW

**Comment by felix920506** [comment]
Couldn't this just be added to the existing fail2ban page?

**Comment by famesjranko** [comment]
Yeah, this is true.  The is my first addition. Happy to make changes

**Comment by felix920506** [comment]
If you think it is better to be is own page then please provide a reason

**Comment by famesjranko** [comment]
Don't have one. Will close and integrate into fail2ban page. Cheers

**Comment by felix920506** [comment]
You can just make changes to this Pr and push them...

**Pull request closed without merging**
