### PR TITLE
Added roku disclaimer in new Subtext to clients

### PR DESCRIPTION
**Pull request by JPVenson**
- Added "Help Text" to clients view.
- Added Roku help text, clarifying disclaimer on roku store that JF requires subscriptions
image
- mitigates https://github.com/jellyfin/jellyfin-roku/issues/507

### CODE REVIEW

**Review by anthonylavado — APPROVED** [review]

**Comment by srcrist** [comment]
You have an extra period there, Venson.

**Comment by anthonylavado** [comment]
Mr. Javascript-lint is mad.

**Comment by JPVenson** [comment]
Whhhhhhhy?
@srcrist old version still in cache. Code submitted is correct :-D

**Comment by JPVenson** [comment]
Lint happy now

**Review by Shadowghost — APPROVED** [review]

**Pull request merged**
