### PR TITLE
add way to configure traefik for jellyfin not running in docker

### PR DESCRIPTION
**Pull request by cedricwalter**

### CODE REVIEW

**Comment by felix920506** [comment]
Please add a description to your pull request and fix the linting issues

**Review by nielsvanvelzen — CHANGES_REQUESTED** [review]
Please fix the linter issues

**Comment by felix920506** [comment]
@cedricwalter please fix the linter issues so we can move forward with this.

**Comment by nielsvanvelzen** [comment]
Closing this pull request as stale. If anyone wants to finish it, please open a new one with the requested changes.

**Pull request closed without merging**
