### PR TITLE
Add jellyfin-vue to client list

### PR DESCRIPTION
**Pull request by ferferga**
Adds Jellyfin Vue to the client page as an "official beta"

Similar in fashion to #232

### CODE REVIEW

**Comment by thornbill** [comment]
I knew I was forgetting something when I added Swiftfin 😅

**Comment by nielsvanvelzen** [comment]
Is the Vue client really in a public beta? It's own README calls it "experimental" and there are no GH releases either so it's not easy to get started with the client. In comparison, the Swiftfin beta releases are tagged and easy to use (sign up for Testflight).

**Comment by ferferga** [comment]
@nielsvanvelzen 

1. Can be used rightaway at https://jf-vue.pages.dev/ (this link is in the PR as well)
2. There are no tags because we never found good reasons to, as everything around it was evolving so quickly. However, we have Docker images that are tagged for every commit sha automatically. At the end of the day it's like web, where in GH we don't provide any built asset, just sources, expecting everyone to build their own or download them from our servers. 
3. There are also Tauri builds for installing it as a native app.

**Comment by nielsvanvelzen** [comment]
Oh no need to defend it, just a "yes" would have been enough :p. For Swiftfin it's quite clear that it's in beta and I didn't find it obvious when looking at the jf-vue repo so that's why I asked.

**Comment by ferferga** [comment]
@nielsvanvelzen Oh no, completely my fault if I came across like that! Sorry if my wording sounded rough because all my intention was to shed some light to your points with a more detailed explanation because you actually are right and we've been lazy at releases and our docs could be improved by a lot :).

**Comment by thornbill** [comment]
I am questioning the placement of this in the list a bit... I tried to generally sort the clients by platform  and it seems to be in the middle of TV clients currently. 😄

**Comment by ferferga** [comment]
@thornbill The ordering of the elements was something I was trying to figure out myself, but didn't found a correlation 😅, so just kept the two official betas together (which are also together the official clients). Thanks for pointing out the actual ordering because not figuring it out was driving me mad :P.

Sounds good to you to place it before Preserve?

**Comment by thornbill** [comment]
Yeah that sounds good to me!

**Review by thornbill — APPROVED** [review]

**Pull request merged**
