### PR TITLE
Update nginx.md

### PR DESCRIPTION
**Pull request by jameskimmel**
small corrections

### CODE REVIEW

**Review by Shadowghost — APPROVED** [review]

**Review by felix920506 — CHANGES_REQUESTED** [review]
The original config was correct. Change the comment to tell users to comment next line to enable TLS 1.0 and 1.1 as your devices will have to be truly ancient to not support TLS 1.2 or newer.

**Comment by jameskimmel** [comment]
> The original config was correct. Change the comment to tell users to comment next line to enable TLS 1.0 and 1.1 as your devices will have to be truly ancient to not support TLS 1.2 or newer.

I don't thinks so.

`Version 1.23.4 and later: the default SSL protocols are TLSv1, TLSv1.1, TLSv1.2, and TLSv1.3`


Source: https://nginx.org/en/docs/http/configuring_https_servers.html

**Comment by felix920506** [comment]
Just because it's the "default" doesn't mean it's better. TLS 1.0 and 1.1 have well documented vulnerabilities at this point so disabling them is more secure.

**Comment by jameskimmel** [comment]
> Just because it's the "default" doesn't mean it's better. TLS 1.0 and 1.1 have well documented vulnerabilities at this point so disabling them is more secure.

I never said so. 
And I agree with you. 
But then we would need to change it the other way round. 
Make TLS 1.2 and 1.3 the default by not commenting them out and write in a comment that users with older devices can comment that line if they have older incompatible devices.

**Comment by felix920506** [comment]
Yes that is what I meant in my review comment

**Review by felix920506 — APPROVED** [review]

**Pull request closed without merging**
