### PR TITLE
Documenation updates

### PR DESCRIPTION
**Pull request by JQuilty**
I've added documentation on where exactly various directories and files are on specific systems. I was able to test with various Linux distros as well as Windows. Unfortunately, I do not have a Mac available at this time to test where the files on MacOS are.

### CODE REVIEW

**Comment by anthonylavado** [comment]
I can provide macOS paths in a few hours.

**Comment by JQuilty** [comment]
@anthonylavado 

Were you able to get the paths for macOS?

**Comment by anthonylavado** [comment]
For the current version of Jellyfin (these will change in future at an undetermined date), these are the paths. As macOS is a BSD derivative, it follows the XDG paths.

Data: `~/.local/share/jellyfin`
Cache: `~/.cache/jellyfin`
Config: `~/.config/jellyfin`
Transcode: `~/.local/share/jellyfin/transcodes`
Web (is embedded in the .app shipped in the .dmg): `/Applications/Jellyfin.app/Contents/Resources/jellyfin-web`
Logs: `~/.local/share/jellyfin/log`

**Review by joshuaboniface — APPROVED** [review]

**Comment by joshuaboniface** [comment]
Approved, but pending addition of the MacOS values cc @anthonylavado

**Comment by nielsvanvelzen** [comment]
@JQuilty can you fix the linter issue and add the MacOS paths, so we can merge this?

**Comment by nielsvanvelzen** [comment]
Closing this pull request as stale. If anyone wants to finish it, please open a new one with the requested changes.

**Pull request closed without merging**
